<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Kos syntax: version 1.0</string>
	<key>fileTypes</key>
	<array>
		<string>kos</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\bkos</string>
	<key>name</key>
	<string>Kos</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.kos</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Match the shebang for Kos executables</string>
			<key>match</key>
			<string>\A(#!).*$\n</string>
			<key>name</key>
			<string>comment.line.number-sign.shebang.kos</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\.)\b(import)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.kos</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)|\n</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.statement.kos</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.import.kos</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>variable.language.import-all.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b([:.])\b</string>
					<key>name</key>
					<string>keyword.control.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.object.kos</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\?</string>
	<!--
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ternary.kos</string>
				</dict>
			</dict>
	-->
			<key>end</key>
			<string>([^:"'`\[\]{}(\)]*)(:)</string>
	<!--
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ternary.kos</string>
				</dict>
			</dict>
	-->
			<key>name</key>
			<string>meta.ternary-if.kos</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=&gt;</string>
			<key>name</key>
			<string>storage.type.arrow.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(const|var)\b(?!\$)</string>
			<key>name</key>
			<string>storage.type.var.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(public)\b(?!\$)</string>
			<key>name</key>
			<string>storage.type.placement.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(assert|async|break|case|catch|continue|default|defer|do|else|fallthrough|for|if|loop|repeat|return|switch|throw|try|while|with)\b(?!\$)</string>
			<key>name</key>
			<string>keyword.control.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(delete|in|instanceof|propertyof|typeof|yield)\b(?!\$)</string>
			<key>name</key>
			<string>keyword.operator.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(extends|get|set|static)\b(?!\$)</string>
			<key>name</key>
			<string>keyword.other.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(__line__|false|true|void)\b</string>
			<key>name</key>
			<string>constant.language.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(this|super)\b</string>
			<key>name</key>
			<string>variable.language.kos</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.)\b(class|constructor|fun)\b</string>
			<key>name</key>
			<string>storage.type.function.kos</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.kos</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.kos</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.kos</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=#)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.kos</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.kos</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.kos</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.kos</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.kos</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.kos</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w|\$)0[xX]\h+\b</string>
					<key>name</key>
					<string>constant.numeric.hex.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\w|\$)0[bB][01]+\b</string>
					<key>name</key>
					<string>constant.numeric.binary.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
					(?&lt;!\w|\$)							    # Ensure word boundary
					[+-]?                                   # Optional sign
					(?&gt;
						(0|[1-9][0-9]*)(\.[0-9]*)?		    # 0 or 1 or 1. or 1.0
						([eEpP][+-]?[0-9]+)?				# Exponent
					)
					(?!\w)									# Ensure word boundary
				</string>
					<key>name</key>
					<string>constant.numeric.decimal.kos</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>%=|\+=|\-=|\*=|/=|\+\+=</string>
					<key>name</key>
					<string>keyword.operator.assignment.compound.arithmetic.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;=|\^=|&lt;&lt;=|&gt;&gt;=|&gt;&gt;&gt;=|\|=</string>
					<key>name</key>
					<string>keyword.operator.assignment.compound.bitwise.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>!=|!=|&lt;=|&gt;=|==|==|&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;&amp;|!|\|\|</string>
					<key>name</key>
					<string>keyword.operator.logical.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;|\||\^|~</string>
					<key>name</key>
					<string>keyword.operator.bitwise.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%|\*|/|\-|\+</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+\+</string>
					<key>name</key>
					<string>keyword.operator.concatenation.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.spread.kos</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword.operator.stream.kos</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>[rR]?"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.kos</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.kos</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.kos</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#escapes</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\\[rn]</string>
							<key>name</key>
							<string>constant.character.escape.newline.kos</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\n</string>
							<key>name</key>
							<string>invalid.illegal.character-not-allowed-here.kos</string>
						</dict>
					</array>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>escapes</key>
				<dict>
					<key>match</key>
					<string>\\([fnrtv\\"0]|x\h{2}|x\{\h+\})</string>
					<key>name</key>
					<string>constant.character.escape.kos</string>
				</dict>
				<key>interpolation</key>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.kos</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.kos</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.kos</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.kos</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.line.kos</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\{</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.curly.kos</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\}</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.brace.curly.kos</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>$self</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.kos</string>
	<key>uuid</key>
	<string>E9A44A42-BD1F-4792-91F3-5301F8D6E0C1</string>
</dict>
</plist>
