image: Visual Studio 2017

platform:
  - x86
  - x64

environment:
  MY_VSSDK150INSTALL: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VSSDK"

install:
  - ps: $env:PATH = 'C:\cygwin64\bin;' + $env:PATH

build_script:
  - cmd: call "%MY_VSSDK150INSTALL%"\..\VC\Auxiliary\Build\vcvarsall.bat %PLATFORM%
  - cmd: sh -c set
  - cmd: sh -c "tests/run seqfail"

branches:
    except:
      - coverity_scan
