platform:
  - x86
  - x64

image:
  - Visual Studio 2017

build_script:
  - cmd: call "%VSSDK150INSTALL%..\VC\vcvarsall.bat" %PLATFORM%
  - cmd: C:\Cygwin\bin\bash -lc set
  - cmd: C:\Cygwin\bin\bahs -lc "tests/run seqfail"

branches:
    except:
      - coverity_scan
