platform:
  - x86
  - x64

environment:
  VSBUILD: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build"

install:
  - ps: $env:PATH = 'C:\cygwin64\bin;' + $env:PATH

build_script:
  - cmd: dir "C:\\cygwin64"
  - cmd: dir "C:\\cygwin64\\bin"
  - cmd: dir "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community"
  - cmd: set
  - cmd: call "%VSBUILD%"\vcvarsall.bat %PLATFORM%
  - cmd: set
  - cmd: sh -c set
  - cmd: sh -c "tests/run seqfail"

branches:
    except:
      - coverity_scan
