extraction:
    cpp:
        index:
            build_command:
                - grep -c ^proc /proc/cpuinfo
                - cc --version
                - make -j $(grep -c ^proc /proc/cpuinfo) interpreter tests
