language: cpp

# Defaults
os: linux
dist: bionic
compiler: gcc

jobs:
    include:
      - name: "Ubuntu 14.04"
        if: branch != coverity_scan
        dist: trusty
        script:
          - tests/run c89 release slowdispatch # Buggy LTO in gcc-4.8

      - name: "Ubuntu 12.04"
        if: branch != coverity_scan
        dist: precise
        script:
          - tests/run c89

      - name: "ARM64"
        if: branch != coverity_scan
        arch: arm64
        script:
          - tests/run c89 release

      - name: "PPC64LE"
        if: branch != coverity_scan
        arch: ppc64le
        script:
          - tests/run c89 release

      - name: "IBM Z"
        if: branch != coverity_scan
        arch: s390x
        script:
          - tests/run cpp14 release
