language: cpp

jobs:
    include:
      - name: "Ubuntu 18.04 + gcc-9"
        if: branch != coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        before_install:
          - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          - sudo apt-get -q update
          - sudo apt-get -y install g++-9
        install:
          - export CXX=g++-9 CC=gcc-9
        script:
          - tests/run default seqfail

      - name: "Ubuntu 16.04"
        if: branch != coverity_scan
        os: linux
        dist: xenial
        compiler: gcc
        script:
          - tests/run c89 release

      - name: "Ubuntu 14.04"
        if: branch != coverity_scan
        os: linux
        dist: trusty
        compiler: gcc
        script:
          - tests/run c89 release slowdispatch # Buggy LTO in gcc-4.8

      - name: "Ubuntu 12.04"
        if: branch != coverity_scan
        os: linux
        dist: precise
        compiler: gcc
        script:
          - tests/run c89

      - name: "ARM64"
        if: branch != coverity_scan
        arch: arm64
        os: linux
        dist: bionic
        compiler: gcc
        script:
          - tests/run c89 release

      - name: "PPC64LE"
        if: branch != coverity_scan
        arch: ppc64le
        os: linux
        dist: bionic
        compiler: gcc
        script:
          - tests/run c89 release

      - name: "IBM Z"
        if: branch != coverity_scan
        arch: s390x
        os: linux
        dist: bionic
        compiler: gcc
        script:
          - tests/run cpp14 release

      - name: "Slow Dispatch"
        if: branch != coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        script:
          - tests/run default slowdispatch

      - name: "Valgrind"
        if: branch != coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        addons:
            apt:
                packages:
                 - valgrind
        script:
          - tests/run valgrind

      - name: "Mad GC"
        if: branch != coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        script:
          - tests/run madgc

      - name: "Coverage"
        if: branch != coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        before_install:
          - pip install --user cpp-coveralls
        script:
          - tests/run gcov
        after_success:
          - coveralls --exclude tests --no-gcov

      - name: "Coverity"
        if: branch = coverity_scan
        os: linux
        dist: bionic
        compiler: gcc
        addons:
            coverity_scan:
                project:
                    name: "kos-lang/kos"
                    description: "Build submitted via Travis CI"
                notification_email: chris@chris.dragan.name
                build_command_prepend: "rm -rf Out"
                build_command: "make -j $(grep -c ^processor /proc/cpuinfo)"
                branch_pattern: coverity_scan
        before_install:
          - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
        script:
          - tests/run c89

      - name: "MacOSX"
        if: branch != coverity_scan
        os: osx
        compiler: clang
        script:
          - tests/run

env:
    global:
      - secure: "NQYyTds2bcp3VLb2mY8QAr+u04KUdgq00Ju+tEOk0z7tuztSLyv+kVXL3W59j4oxrrFwWSBqELgTp/ybj+WEwmJ7y9u/cA0gbiTJB/LpreP9PoxSK/zlpzsTLRFr6SzXpxoUpsKfmP7C2b08tnqb89PX5tU/sU4ooEkGCtXc/jZ7Fnu3MIv7sDrmOEAVpcDE5iCQOKxxVailuP1GglgZwcOjRfclmCdISyRjxOVXuWsar1AXiB5klMm1sUISY/UJm4NUnjkwkKLVW0+t46dYzvmOZIdvDaAnvIeXoVoaQw3s6BxYmbk9QqvigFK3RU72reshvxtuQFM0dmozOffx1vlTHFsXU2gGvGhBUO7toFc9hnFyiyumAlNnOmPcCq/ilz0NPJjHkcV0Xsf/XGlFLHpNYXpZ/nlGlO5jAQI3YQ8qVk/jOJYF4fqupH96faQZnsjpJ6u0cIMd1xBZ/nPm0HYrK7aub1mZcKtOlTpgATBqyjrBLxophm0sVa7JRdIKevndMijzNLHXSQaj+je+pNHsxql6HCvEFBaq9x4OOZVyFaWDbVdJoslP3e88SaL2hZRV1Qh6xZcM86sB2SMcDjpq5LmF9ydiJcg/Mhxkz+9/miUR82lPG4P3V/dmIKJz4oJbPy+G0F0zST0Zl/nxzcRJry500wcsSfs1aVOwIkg="
