language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc

        - os: linux
          compiler: clang

        - os: osx
          compiler: clang

script:
    - tests/run gcov
