#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2020 Chris Dragan

set -e

[ -n "$AFL" ] || AFL=/usr
export AFL_PATH="$AFL"/lib/afl
export CC="$AFL"/bin/afl-clang-fast
export CXX="$AFL"/bin/afl-clang-fast++
export AFL_HARDEN=1
export AFL_NO_AFFINITY=1
#export AFL_NO_ARITH=1

[ -n "$JOBS" ] || JOBS="$(grep -c ^processor /proc/cpuinfo)"

rm -rf Out/debug
make interpreter debug=1 fuzz=1 -j "$JOBS"

run_afl()
{
    [ $# -eq 2 ] || exit 1
    echo "Spawning AFL with $@..."
    "$AFL"/bin/afl-fuzz -i tests/kos_fuzz_interpreter_corpus \
                        -o tests/kos_fuzz_interpreter_afl \
                        -x tests/kos_fuzz_interpreter_dict \
                        -t 1000+ \
                        "$@" \
                        -- Out/debug/interpreter/kos \
                        2>&1 > Out/debug/$2.log
}

if [ $JOBS -eq 1 ]; then
    run_afl -M fuzz0
else
    run_afl -M fuzz0 &
    if [ $JOBS -gt 2 ]; then
        for JOB in $(seq $(($JOBS - 2))); do
            run_afl -S "fuzz$JOB" &
        done
    fi
    run_afl -S "fuzz$(($JOBS - 1))"
fi
