#!/bin/sh

# Copyright (c) 2014-2020 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -e

export CFLAGS=-fsanitize=fuzzer-no-link,address
export LDFLAGS=-fsanitize=fuzzer,address
export CC=clang
export CXX=clang++

show_help()
{
    echo "Usage: tests/fuzz [OPTIONS]"
    echo
    echo "Options:"
    echo "    --test NAME       Run test: interpreter (default) or compiler"
    echo "    --merge           Merge corpus (deduplicate, etc.)"
    echo "    --minimize NAME   Minimize a crashing test case"
    echo "    -j N              Run N jobs (default is autodetect)"
}

if [ -z "$JOBS" ]; then
    case "$(uname -s)" in
        Linux)                                   JOBS="$(grep -c ^processor /proc/cpuinfo)" ;;
        Darwin|FreeBSD|OpenBSD|NetBSD|DragonFly) JOBS="$(sysctl -n hw.ncpu)" ;;
        CYGWIN*|MINGW*|MSYS*)                    JOBS="$NUMBER_OF_PROCESSORS" ;;
        Haiku|BeOS)                              JOBS="$(sysinfo | grep -c 'CPU #')" ;;
        *)                                       JOBS=2 ;;
    esac
fi

CORPORA_BASE=(
    kos_fuzz_interpreter
    kos_fuzz_compiler
)

PWD="$(pwd)"
OUT="$PWD/Out/debug/tests"
FUZZ="${CORPORA_BASE[0]}"
DICT="$PWD/tests/kos_fuzz_interpreter_dict"
MERGE=0
MINIMIZE=""

# Handle command line args
while [ $# -gt 0 ]; do
    case "$1" in
        --merge)    MERGE=1 ;;
        --minimize) shift ; MINIMIZE="$1" ;;
        --test)     shift ; FUZZ="kos_fuzz_$1" ;;
        -j)         shift ; JOBS="$1" ;;
        -h|--help)  show_help ; exit 0 ;;
        *)          echo "Unrecognized parameter: $1" >&2 ; echo ; show_help ; exit 1 ;;
    esac
    shift
done

# Get list of corpora (input and output)
CORPUS="$PWD/tests/${FUZZ}_corpus"
INPUT_CORPORA=( )
for CUR_CORP in "${CORPORA_BASE[@]}"; do
    [ "$CUR_CORP" = "$FUZZ" ] && continue
    for CORP_SUFFIX in _corpus _afl; do
        CORP_DIR="$PWD/tests/${CUR_CORP}${CORP_SUFFIX}"
        [ -d "$CORP_DIR" ] && INPUT_CORPORA+=( "$CORP_DIR" )
    done
done

echo "Using $JOBS jobs"

[ -f "$OUT/$FUZZ" ] || rm -rf Out

make -k -j "$JOBS" fuzz debug=1 fuzz=1 strict=1 CLANG_VER=c99 --warn-undefined-variables

cd "$OUT"

merge_corpus()
{
    "./$FUZZ" -merge=1 "$CORPUS" "$@"
}

if [ "$MERGE" = "1" -a -d "$CORPUS" ]; then
    mv "$CORPUS" "$CORPUS.old"
    mkdir -p "$CORPUS"
    if [ ${#INPUT_CORPORA[*]} -gt 0 ]; then
        merge_corpus "$CORPUS.old" "${INPUT_CORPORA[@]}"
        rm -rf "${INPUT_CORPORA[@]}"
    else
        merge_corpus "$CORPUS.old"
    fi
    rm -rf "$CORPUS.old"
    exit 0
fi

if [ -n "$MINIMIZE" ]; then
    "./$FUZZ" -minimize_crash=1 -runs=10000 "$MINIMIZE"
    exit 0
fi

run_parallel_fuzzer()
{
    "./$FUZZ" "-jobs=$JOBS" "-workers=$JOBS" "-dict=$DICT" "$@"
}

mkdir -p "$CORPUS"
run_parallel_fuzzer "$CORPUS" "${INPUT_CORPORA[@]}"
