#!/bin/sh

# Copyright (c) 2014-2019 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -e

[ -n "$AFL" ] || AFL=/usr
export AFL_PATH="$AFL"/lib/afl
export CC="$AFL"/bin/afl-clang-fast
export CXX="$AFL"/bin/afl-clang-fast++
export AFL_HARDEN=1
export AFL_NO_AFFINITY=1
#export AFL_NO_ARITH=1

[ -n "$JOBS" ] || JOBS="$(grep -c ^processor /proc/cpuinfo)"

rm -rf Out/debug
make build.interpreter debug=1 fuzz=1 -j "$JOBS"

run_afl()
{
    [ $# -eq 2 ] || exit 1
    echo "Spawning AFL with $@..."
    "$AFL"/bin/afl-fuzz -i tests/kos_fuzz_interpreter_corpus \
                        -o tests/kos_fuzz_interpreter_afl \
                        -x tests/kos_fuzz_interpreter_dict \
                        -t 1000+ \
                        "$@" \
                        -- Out/debug/interpreter/kos \
                        2>&1 > Out/debug/$2.log
}

if [ $JOBS -eq 1 ]; then
    run_afl -M fuzz0
else
    run_afl -M fuzz0 &
    if [ $JOBS -gt 2 ]; then
        for JOB in $(seq $(($JOBS - 2))); do
            run_afl -S "fuzz$JOB" &
        done
    fi
    run_afl -S "fuzz$(($JOBS - 1))"
fi
