#!/bin/sh

# Copyright (c) 2014-2020 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -e

TEST="$1"
OUTPUT="$2/print_heap_test.txt"

"$TEST" > "$OUTPUT" 2>&1

COUNT=$(grep -c "^total" "$OUTPUT" || true)
if [ "$COUNT" != "1" ]; then
    if [ "$COUNT" = "0" ]; then
        echo "Missing heap summary" >&2
    else
        echo "Unexpected output" >&2
        grep "^total" "$OUTPUT" | sed "s/^/> /" >&2
    fi
    exit 1
fi

if ! grep -q "total 1 pages used,.*, [0-9]* bytes malloc'd" "$OUTPUT"; then
    echo "Unexpected output" >&2
    grep "^total" "$OUTPUT" | sed "s/^/> /" >&2
    exit 1
fi
