#!/bin/sh

# Copyright (c) 2014-2018 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -e

RUN_C89=1
RUN_CPP14=1
RUN_RELEASE=1
RUN_ASAN=1
RUN_VALGRIND=0
RUN_GCOV=0
RUN_SEQFAIL=0

if [ $# -gt 0 ]; then
    if [ "$1" = "default" ]; then
        shift
    else
        RUN_C89=0
        RUN_CPP14=0
        RUN_RELEASE=0
        RUN_ASAN=0
    fi
fi

while [ $# -gt 0 ]; do
    case $1 in
        c89)      RUN_C89=1      ;;
        cpp14)    RUN_CPP14=1    ;;
        release)  RUN_RELEASE=1  ;;
        asan)     RUN_ASAN=1     ;;
        valgrind) RUN_VALGRIND=1 ;;
        gcov)     RUN_GCOV=1     ;;
        seqfail)  RUN_SEQFAIL=1  ;;
        *)        echo "Error: Unrecognized parameter - $1" >&2 ; exit 1
    esac
    shift
done

UNAME=$(uname -s)

if [ -z "$JOBS" ]; then
    case "$UNAME" in
        Linux)                                   JOBS="$(grep -c ^processor /proc/cpuinfo)" ;;
        Darwin|FreeBSD|OpenBSD|NetBSD|DragonFly) JOBS="$(sysctl -n hw.ncpu)" ;;
        CYGWIN*|MINGW*|MSYS*)                    JOBS="$NUMBER_OF_PROCESSORS" ; UNAME="Windows" ;;
        Haiku|BeOS)                              JOBS="$(sysinfo | grep -c 'CPU #')" ;;
        *)                                       JOBS=2 ;;
    esac
fi

echo "Using $JOBS jobs"

# Parallel tests use this env var to run number of threads proportional to the number of CPUs
export TEST_CPUS="$JOBS"

# Optimize for the current architecture
export CONFIG_NATIVE=1

# Save for overriding
ORIG_JOBS=$JOBS

runtests()
{
    echo "***************************************************************************"
    local MODE
    MODE="RELEASE"
    [ "$CONFIG_DEBUG" = "1" ] && MODE="DEBUG"

    local PRINT_CLANG
    PRINT_CLANG=$(echo "$1" | tr 'c' 'C')

    local PRINT_CPPLANG
    PRINT_CPPLANG=$(echo "$2" | tr 'c' 'C')

    local PRINT_LANG
    if [ "$UNAME" = "Windows" ]; then
        PRINT_LANG="C and C++"
        echo "$1" | grep -q "c++" && PRINT_LANG="C++"
    else
        PRINT_LANG="$PRINT_CLANG and $PRINT_CPPLANG"
        [ "$1" = "$2" ] && PRINT_LANG="$PRINT_CLANG"
    fi

    local WITH_TOOL
    WITH_TOOL=""
    [ -n "$CONFIG_TOOL" ] && WITH_TOOL=" with $CONFIG_TOOL"
    [ -n "$CONFIG_GCOV" ] && WITH_TOOL=" with gcov"

    if [ -n "$SANITIZER" ]; then
        local CFLAGS
        local LDFLAGS
        CFLAGS="-fsanitize=$SANITIZER"
        LDFLAGS="-fsanitize=$SANITIZER"
        if [ "$UNAME" = "Linux" ]; then
            # gcc bug WAR
            LDFLAGS="$LDFLAGS -fuse-ld=gold"
        fi
        export CFLAGS
        export LDFLAGS
        WITH_TOOL="$WITH_TOOL with $SANITIZER sanitizer"
    fi

    echo "Testing $MODE as $PRINT_LANG$WITH_TOOL"
    echo "***************************************************************************"

    [ "$3" = "noclean" ] || rm -rf Out
    make -k -j "$JOBS" test CLANG_VER=$1 CPPLANG_VER=$2 CONFIG_STRICT=1 --warn-undefined-variables
}

cd "$(dirname $0)"/..

unset SANITIZER
unset CONFIG_TOOL
unset CONFIG_GCOV
unset CONFIG_SEQFAIL
export CONFIG_DEBUG=1

if [ "$RUN_C89" = "1" -o "$RUN_VALGRIND" = "1" ]; then
    runtests c89 c++98
fi

if [ "$RUN_VALGRIND" = "1" ]; then
    if [ "$UNAME" != "Linux" ]; then
        echo "Error: Valgrind is only supported on Linux!" >&2
        exit 1
    fi

    if [ "$(which valgrind 2>/dev/null)" = "" ]; then
        echo "Error: Valgrind not found!" >&2
        exit 1
    fi

    export CONFIG_TOOL="valgrind --error-exitcode=1 --track-origins=yes"

    # Limit number of jobs to reduce memory pressure
    JOBS=$(($JOBS / 2))
    [ $JOBS -gt 8 ] && JOBS=8

    TEST_CPUS=2 runtests c89 c++98 noclean

    unset CONFIG_TOOL
    JOBS=$ORIG_JOBS
fi

if [ "$RUN_ASAN" = "1" ]; then
    if [ "$UNAME" != "Darwin" -a "$UNAME" != "Linux" ]; then
        echo "Error: Address sanitizer is only supported on MacOSX and Linux!" >&2
        exit 1
    fi

    export SANITIZER="address"
    [ $JOBS -gt 2 ] && JOBS=$(($JOBS / 2))
    [ $JOBS = 0 ] && JOBS=1
    RUN_CPP14="1"
fi

if [ "$RUN_SEQFAIL" = "1" ]; then
    export CONFIG_SEQFAIL=1
    RUN_CPP14="1"
fi

if [ "$RUN_CPP14" = "1" ]; then
    runtests c++14 c++14
fi

unset SANITIZER
unset CONFIG_SEQFAIL
JOBS=$ORIG_JOBS

unset CONFIG_DEBUG
if [ "$RUN_RELEASE" = "1" ]; then
    runtests c11 c++11
fi

if [ "$RUN_GCOV" = "1" ]; then
    if [ "$UNAME" = "Windows" ]; then
        echo "Error: gcov not supported on Windows!" >&2
        exit 1
    fi
    export CONFIG_GCOV=1
    export CONFIG_DEBUG=1
    export CONFIG_SEQFAIL=1
    runtests c99 c++14
    unset CONFIG_GCOV
    unset CONFIG_DEBUG
    unset CONFIG_SEQFAIL
else
    rm -rf Out
fi
