#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2023 Chris Dragan

set -e

UNAME=$(uname -s)
MAKE=make

if [ -z "$JOBS" ]; then
    case "$UNAME" in
        Linux)                                   JOBS="$(grep -c ^processor /proc/cpuinfo)" ;;
        Darwin|FreeBSD|OpenBSD|NetBSD|DragonFly) JOBS="$(sysctl -n hw.ncpu)" ;;
        CYGWIN*|MINGW*|MSYS*)                    JOBS="$NUMBER_OF_PROCESSORS" ; UNAME="Windows" ;;
        Haiku|BeOS)                              JOBS="$(sysinfo | grep -c 'CPU #')" ;;
        *)                                       JOBS=2 ;;
    esac
    [ $JOBS -lt 32 ] || JOBS=32
fi

case "$UNAME" in
    FreeBSD|OpenBSD|NetBSD|DragonFly)
        MAKE=gmake
        ;;
esac

echo "Using $JOBS jobs"

die()
{
    echo "$@"
    exit 1
}

KOS=1
PY=1
JS=1

if [ -n "$JS_INTERPRETER" ]; then
    [ -d "$JS_INTERPRETER" ] || JS=0
else
    JS=0
fi

if [ $# -gt 0 ]; then
    KOS=0
    PY=0
    JS=0
    while [ $# -gt 0 ]; do
        case "$1" in
            kos) KOS=1 ;;
            py)  PY=1  ;;
            js)  JS=1  ;;
            *)   die "Invalid option: $1"
        esac
        shift
    done
fi

if [ $JS = 1 ]; then
    [ -n "$JS_INTERPRETER" ] || die "JS_INTERPRETER not specified"
    [ -f "$JS_INTERPRETER"/Makefile ] || die "$JS_INTERPRETER is not accessible"
fi

rm -rf Out

$MAKE -k -j "$JOBS" time_us interpreter native=1

if [ $JS = 1 ]; then
    rm -rf "$JS_INTERPRETER/Out"
    $MAKE -k -j "$JOBS" native=1 -C "$JS_INTERPRETER"
fi

runtest()
{
    local LOOPS
    LOOPS="$1"
    shift

    local SCRIPT
    SCRIPT="$1"

    if echo "$SCRIPT" | grep -q "\.kos$"; then [ $KOS = 1 ] || return 0; fi
    if echo "$SCRIPT" | grep -q "\.py$" ; then [ $PY  = 1 ] || return 0; fi
    if echo "$SCRIPT" | grep -q "\.js$" ; then [ $JS  = 1 ] || return 0; fi

    local PREFIX
    PREFIX=""

    echo "$SCRIPT" | grep -q "\.py$"  && PREFIX=python3
    echo "$SCRIPT" | grep -q "\.kos$" && PREFIX=Out/release/interpreter/kos
    echo "$SCRIPT" | grep -q "\.js$"  && PREFIX=Out/release/js/js

    tests/perf/measure -t "$1" -n "$LOOPS" $PREFIX "$@"
}

runtest 20 doc/extract_docs.kos modules/*.kos modules/*.c

runtest 10 tests/perf/primes.kos
runtest 10 tests/perf/primes.py
runtest 10 tests/perf/primes.js

runtest 10 tests/perf/mandel_int.kos
runtest 10 tests/perf/mandel_int.py

runtest 10 tests/perf/mandel_float.kos
runtest 10 tests/perf/mandel_float.py

runtest 10 tests/perf/array_for_in.kos
runtest 10 tests/perf/array_for_in.py
runtest 10 tests/perf/array_for_in.js

runtest 10 tests/perf/array_index_iter.kos
runtest 10 tests/perf/array_index_iter.py
runtest 10 tests/perf/array_index_iter.js

runtest 10 tests/perf/object_for_in.kos
runtest 10 tests/perf/object_for_in.py
runtest 10 tests/perf/object_for_in.js

runtest 10 tests/perf/sort_strings.kos
runtest 10 tests/perf/sort_strings.py
runtest 10 tests/perf/sort_strings.js

runtest 10 tests/perf/fib_class_flat.kos
runtest 10 tests/perf/fib_class.py
runtest 10 tests/perf/fib_class_flat.js

runtest 10 tests/perf/fib_class_proto.kos
runtest 10 tests/perf/fib_class_proto.js
