#!/bin/sh

# Copyright (c) 2014-2017 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <kos> <output_dir>"
    exit 1
fi

KOS="$1"
OUTPUT="$2/dash_c"

"$KOS" -c 'print_("Hello, ")
print("Kos!")
' > "$OUTPUT"

CONTENTS=`cat "$OUTPUT"`

if [ "$CONTENTS" != 'Hello, Kos!' ]; then
    echo "Expected output to contain: \"Hello, Kos\!\", but it is different" >&2
    cat "$OUTPUT"
    exit 1
fi

"$KOS" -c "print(integer(args[0]) + integer(args[1]))" 20 -5 > "$OUTPUT"

CONTENTS=`cat "$OUTPUT"`

if [ "$CONTENTS" != "15" ]; then
    echo "Expected output to contain: \"15\", but it is different" >&2
    cat "$OUTPUT"
    exit 1
fi
