#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2022 Chris Dragan

set -e

if [ $# -ne 2 ]; then
    echo "$0: Invalid arguments"
    exit 1
fi

KOS="$1"
DIR="$2"

env KOSDISASM=1 "$KOS" "$(dirname "$0")"/disasm.kos | sed "1,/Disassembling module: disasm/ d" > "$DIR"/disasm.txt

diff -w "$(dirname "$0")"/disasm.txt "$DIR"/disasm.txt
