#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2020 Chris Dragan

set -e

if [ $# -lt 2 ]; then
    echo "Usage: $0 <dir> <command> ..."
    exit 1
fi

OUTPUT="$1"
shift

mkdir -p "$OUTPUT"

EC=0
"$@" >"$OUTPUT/stdout" 2>"$OUTPUT/stderr" || EC=$?

if [ "$EC" != "1" ]; then
    echo "Failed command: $@"
    echo "Unexpected exit code: $EC"
    echo "stdout:"
    sed 's/^/    /' "$OUTPUT/stdout"
    echo "stderr:"
    sed 's/^/    /' "$OUTPUT/stderr"
    exit 1
fi

if [ $(wc -c < "$OUTPUT/stdout") != 0 ]; then
    echo "Failed command: $@"
    echo "Unexpected output on stdout (expected no output)"
    echo "stdout:"
    sed 's/^/    /' "$OUTPUT/stdout"
    exit 1
fi

if [ "$1" != "valgrind" ]; then
    if [ $(wc -l < "$OUTPUT/stderr") -gt 3 ] && ! grep -q "stack overflow" < "$OUTPUT/stderr"; then
        echo "Failed command: $@"
        echo "Unexpected output on stderr (expected at most 3 lines)"
        echo "stderr:"
        sed 's/^/    /' "$OUTPUT/stderr"
        exit 1
    fi
fi
