#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2020 Chris Dragan

set -e

if [ $# -ne 2 ]; then
    echo "$0: Invalid arguments"
    exit 1
fi

KOS="$1"
DIR="$2"

"$KOS" "$(dirname "$0")"/module_base_print.kos | tr -d '\r' > "$DIR"/module_base_print.txt

tr -d '\r' < "$(dirname "$0")"/module_base_print.txt > "$DIR"/module_base_print_expected.txt

diff "$DIR"/module_base_print_expected.txt "$DIR"/module_base_print.txt
