#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2023 Chris Dragan

set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <kos> <output_dir>"
    exit 1
fi

UNAME=`uname -s`
case "$UNAME" in
    CYGWIN*|MINGW*|MSYS*) UNAME="Windows" ;;
esac

remove_cr()
{
    tr -d '\r'
}

KOS="$1"
OUTPUT="$2/module_os_spawn"

run()
{
    "$KOS" -c "$1" | remove_cr > "$OUTPUT"
}

run_shell()
{
    if [ "$UNAME" = "Windows" ]; then
        local ARGS
        ARGS=""
        while [ $# -gt 0 ]; do
            ARGS="$ARGS, \"$1\""
            shift
        done
        run 'import os; os.spawn(program="cmd", args=["/c"'"$ARGS"'], inherit_env=false)'
    else
        run 'import os; os.spawn("/bin/sh", ["-c", "'"$*"'"])'
    fi
}

##############################################################################
# Run simple shell script via /bin/sh

run_shell "echo" "Hello_Kos" > "$OUTPUT"

CONTENTS=`cat "$OUTPUT"`

if [ "$CONTENTS" != "Hello_Kos" ]; then
    echo "$LINENO: Error: Expected output to contain: \"Hello_Kos\", but it is different" >&2
    cat "$OUTPUT"
    exit 1
fi

rm "$OUTPUT"
