#!/bin/sh

# SPDX-License-Identifier: MIT
# Copyright (c) 2014-2021 Chris Dragan

set -e

die()
{
    echo "$@"
    exit 1
}

[ -f "$1" ] || die "Error: Missing '$1'"
[ -f "$2" ] || die "Error: Missing '$2'"
[ -f "$3" ] || die "Error: Missing '$3'"

rm -rf "$4"

"$1" "$2" < "$3" > "$4".tmp

[ -f "$3.expected" ] || die "Error: Missing '$3.expected'"

sed "/Kos .* interactive interpreter/s/[0-9]*\.[0-9]*/0.1/" < "$4".tmp > "$4"

diff "$3.expected" "$4"
