#
# Copyright (c) 2014-2016 Chris Dragan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#

module = kos_lang
depth  = lang

c_files  = kos_array.c
c_files += kos_buffer.c
c_files += kos_context.c
c_files += kos_compiler.c
c_files += kos_compiler_optim.c
c_files += kos_compiler_vars.c
c_files += kos_file.c
c_files += kos_lexer.c
c_files += kos_malloc.c
c_files += kos_memory.c
c_files += kos_misc.c
c_files += kos_module.c
c_files += kos_object_alloc.c
c_files += kos_object_base.c
c_files += kos_object.c
c_files += kos_string.c
c_files += kos_parser.c
c_files += kos_red_black.c
c_files += kos_threads.c
c_files += kos_utf8.c
c_files += kos_vm.c

cpp_files = kos_cpp_api.cpp

include ../build/rules.mk
include ../build/lib.mk

