name: Package

on:
  create

jobs:
  package:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04

    runs-on: ${{ matrix.os }}

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: interpreter/create_package.sh "$GITHUB_REF"
