name: Package

on:
  create

jobs:
  default:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04

    runs-on: ${{ matrix.os }}

    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: interpreter/create_package.sh "$GITHUB_REF"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Out/release/kos-*.*

  windows:
    runs-on: windows-latest

    timeout-minutes: 10

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: diffutils
      - uses: actions/checkout@v2
      - name: Remove link.exe from MSYS2
        shell: msys2 {0}
        run: rm -f /bin/link.exe
      - name: Add path to WiX Toolset
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Package
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          msys2 -c "interpreter/create_package.sh $GITHUB_REF"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Out/release/Kos-*.*
