name: Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_number: ${{ steps.version.outputs.version_number }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Set version number
        run: |
          echo "::set-output name=version::${GITHUB_REF#*/*/}"
          echo "::set-output name=version_number::${GITHUB_REF#*/*/v}"
        id: version
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: true
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: Release ${{ steps.version.outputs.version }}

  default:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04

    runs-on: ${{ matrix.os }}
    needs: release
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: interpreter/create_package.sh ${{ needs.release.outputs.version }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Out/release/kos-${{ needs.release.outputs.version_number }}.*
      - name: Upload amd64 deb
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'ubuntu-16.04' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-linux-amd64.deb
          asset_name: kos-${{ needs.release.outputs.version_number }}-linux-amd64.deb
          asset_content_type: application/octet-stream
      - name: Upload amd64 deb sha
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'ubuntu-16.04' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-linux-amd64.deb.sha
          asset_name: kos-${{ needs.release.outputs.version_number }}-linux-amd64.deb.sha
          asset_content_type: application/octet-stream
      - name: Upload amd64 pkg
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-macos-amd64.pkg
          asset_name: kos-${{ needs.release.outputs.version_number }}-macos-amd64.pkg
          asset_content_type: application/octet-stream
      - name: Upload amd64 pkg sha
        uses: actions/upload-release-asset@v1
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-macos-amd64.pkg.sha
          asset_name: kos-${{ needs.release.outputs.version_number }}-macos-amd64.pkg.sha
          asset_content_type: application/octet-stream

  windows:
    runs-on: windows-latest
    needs: release
    timeout-minutes: 10

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: diffutils
      - uses: actions/checkout@v2
      - name: Remove link.exe from MSYS2
        shell: msys2 {0}
        run: rm -f /bin/link.exe
      - name: Add path to WiX Toolset
        run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Package
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          msys2 -c "interpreter/create_package.sh ${{ needs.release.outputs.version }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: Out/release/kos-${{ needs.release.outputs.version_number }}.*
      - name: Upload amd64 msi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-windows-amd64.msi
          asset_name: kos-${{ needs.release.outputs.version_number }}-windows-amd64.msi
          asset_content_type: application/octet-stream
      - name: Upload amd64 msi sha
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: Out/release/kos-${{ needs.release.outputs.version_number }}-windows-amd64.msi.sha
          asset_name: kos-${{ needs.release.outputs.version_number }}-windows-amd64.msi.sha
          asset_content_type: application/octet-stream
