name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  basic_test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - macos-latest
        test:
          - c89
          - release
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: tests/run ${{ matrix.test }}

  unit_from_fuzz:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test
        run: tests/fuzz --unit

  full_test:
    strategy:
      matrix:
        test:
          - asan seqfail
          - madgc
          - asan slowdispatch
          - asan deepstack
          - valgrind
          - lcov
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        if: ${{ matrix.test == 'valgrind' }}
        run: |
          sudo apt update
          sudo apt install valgrind
      - name: Install lcov
        if: ${{ matrix.test == 'lcov' }}
        run: |
          sudo apt update
          sudo apt install lcov
      - name: Test
        run: tests/run ${{ matrix.test }}
      - name: Coveralls
        if: ${{ matrix.test == 'lcov' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: Out/debug/kos.info

  windows-32:
    strategy:
      matrix:
        target:
          - x86
        test:
          - c89
          - release
          - seqfail
    runs-on: windows-2019
    timeout-minutes: 10
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          install: diffutils
      - uses: actions/checkout@v4
      - name: Remove link.exe from MSYS2
        shell: msys2 {0}
        run: rm -f /bin/link.exe
      - name: Test
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.target }}
          msys2 -c "tests/run ${{ matrix.test }}"

  windows-64:
    strategy:
      matrix:
        target:
          - x64
          - x86
        test:
          - c89
          - release
          - seqfail
    runs-on: windows-2022
    timeout-minutes: 10
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          install: diffutils
      - uses: actions/checkout@v4
      - name: Test
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.target }}
          msys2 -c "tests/run ${{ matrix.test }}"
